#!/usr/bin/env bash
set -Eeuo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP_DIR"

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-3000}"

load_env_file() {
  local env_file="$1"
  if [[ -f "$env_file" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$env_file"
    set +a
  fi
}

# Load the self-hosted backend env first and remember it. The app .env may
# contain preview/cloud values from development, but production redirects must
# always use the VPS backend where migrations are applied.
load_env_file "/opt/supabase-prod/.env"
SELFHOST_SUPABASE_URL="${SUPABASE_URL:-${API_EXTERNAL_URL:-https://api.adspx.com}}"
SELFHOST_PUBLISHABLE_KEY="${ANON_KEY:-${SUPABASE_PUBLISHABLE_KEY:-}}"
SELFHOST_SERVICE_ROLE_KEY="${SERVICE_ROLE_KEY:-${SUPABASE_SERVICE_ROLE_KEY:-}}"

load_env_file "$APP_DIR/.env"

# Self-hosted installs sometimes use the shorter key names generated by the
# backend stack. Force the app runtime back to the VPS backend after .env loads.
export SUPABASE_URL="${SELFHOST_SUPABASE_URL:-${SUPABASE_URL:-${API_EXTERNAL_URL:-https://api.adspx.com}}}"
export SUPABASE_PUBLISHABLE_KEY="${SELFHOST_PUBLISHABLE_KEY:-${SUPABASE_PUBLISHABLE_KEY:-${ANON_KEY:-}}}"
export SUPABASE_SERVICE_ROLE_KEY="${SELFHOST_SERVICE_ROLE_KEY:-${SUPABASE_SERVICE_ROLE_KEY:-${SERVICE_ROLE_KEY:-}}}"

echo "Backend env: SUPABASE_URL=$([[ -n "${SUPABASE_URL:-}" ]] && echo set || echo missing) SUPABASE_SERVICE_ROLE_KEY=$([[ -n "${SUPABASE_SERVICE_ROLE_KEY:-}" ]] && echo set || echo missing) SUPABASE_PUBLISHABLE_KEY=$([[ -n "${SUPABASE_PUBLISHABLE_KEY:-}" ]] && echo set || echo missing)"

if [[ ! -f ".output/server/index.mjs" ]]; then
  echo "Missing .output/server/index.mjs. Run: bun run build" >&2
  exit 1
fi

exec node .output/server/index.mjs --host "$HOST" --port "$PORT"