#!/usr/bin/env bash
set -Eeuo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP_DIR"

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-3000}"

if [[ -f "$APP_DIR/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$APP_DIR/.env"
  set +a
fi

# Self-hosted installs sometimes use the shorter key names generated by the
# backend stack. Normalize them to the names used by the app runtime.
export SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-${SERVICE_ROLE_KEY:-}}"
export SUPABASE_PUBLISHABLE_KEY="${SUPABASE_PUBLISHABLE_KEY:-${ANON_KEY:-}}"

echo "Backend env: SUPABASE_URL=$([[ -n "${SUPABASE_URL:-}" ]] && echo set || echo missing) SUPABASE_SERVICE_ROLE_KEY=$([[ -n "${SUPABASE_SERVICE_ROLE_KEY:-}" ]] && echo set || echo missing) SUPABASE_PUBLISHABLE_KEY=$([[ -n "${SUPABASE_PUBLISHABLE_KEY:-}" ]] && echo set || echo missing)"

if [[ ! -f ".output/server/index.mjs" ]]; then
  echo "Missing .output/server/index.mjs. Run: bun run build" >&2
  exit 1
fi

exec node .output/server/index.mjs --host "$HOST" --port "$PORT"