#!/usr/bin/env bash
set -Eeuo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP_DIR"

HOST="${HOST:-0.0.0.0}"
PORT="${PORT:-3000}"

load_env_file() {
  local env_file="$1"
  if [[ -f "$env_file" ]]; then
    set -a
    # shellcheck disable=SC1090
    source "$env_file"
    set +a
  fi
}

# Load the self-hosted backend secrets first, then allow the app .env to
# override public frontend/runtime values such as SUPABASE_URL.
load_env_file "/opt/supabase-prod/.env"
load_env_file "$APP_DIR/.env"

# Self-hosted installs sometimes use the shorter key names generated by the
# backend stack. Normalize them to the names used by the app runtime.
export SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-${SERVICE_ROLE_KEY:-}}"
export SUPABASE_PUBLISHABLE_KEY="${SUPABASE_PUBLISHABLE_KEY:-${ANON_KEY:-}}"
export SUPABASE_URL="${SUPABASE_URL:-${API_EXTERNAL_URL:-https://api.adspx.com}}"

echo "Backend env: SUPABASE_URL=$([[ -n "${SUPABASE_URL:-}" ]] && echo set || echo missing) SUPABASE_SERVICE_ROLE_KEY=$([[ -n "${SUPABASE_SERVICE_ROLE_KEY:-}" ]] && echo set || echo missing) SUPABASE_PUBLISHABLE_KEY=$([[ -n "${SUPABASE_PUBLISHABLE_KEY:-}" ]] && echo set || echo missing)"

if [[ ! -f ".output/server/index.mjs" ]]; then
  echo "Missing .output/server/index.mjs. Run: bun run build" >&2
  exit 1
fi

exec node .output/server/index.mjs --host "$HOST" --port "$PORT"